.env
.github/CODEOWNERS
.gitignore
package.json
pnpm-lock.yaml
src/api/axiosInstance.ts

> close #3 
Axios 초기 세팅
- axios 패키지 설치
- axiosInstance.ts 파일로 Axios 인스턴스 생성
- 응답 인터셉터 기본 구조 추가
- CODEOWNERS 파일 추가해 PR 자동 리뷰어 설정
- 응답 인터셉터에 401, 500 에러에 대한 콘솔 로그만 우선 추가해두었습니다.
- 추후 서버 응답 구조가 확정되면 handleError 함수로 분리하고 사용자 대응 처리도 추가할 예정이에요!

[Init]: Axios 초기 세팅 및 자동 리뷰어 설정

---

.github/CODEOWNERS
.gitignore
package.json
pnpm-lock.yaml
src/api/axiosInstance.ts
vite.config.ts

> close #6 
Svgr 세팅했습니다
- Svgr 세팅
사용법
1. public/svg 폴더에 svg파일 넣기
2. `pnpm svgr` 실행
3. asset/svg/ 안에 예쁘게 들어가 있는 이모티콘 감상하기
한 가지 제안할 점이 있습니다.
아이콘 저장할 때 앞에 ic_붙이는걸로 컨벤션 맞추는 게 어떨까요?
ex) ic_check 이런 식으로
아이콘만 빠르게 필터링 가능하고. 파일명만 봐도 아이콘이란걸 알 수 있어서 헷갈리지 않을 것 같습니다.
**머지 전에 확인용 아이콘은 삭제 후 머지 예정입니다.

[init/#6] svgr setting

---

package.json
pnpm-lock.yaml
vite.config.ts

> close #9
Vanilla Extract 설정
- Vanilla Extract 설치
- Vanilla Extract 연동
스타일링 정상적으로 반영된 것 확인했습니다 !

[Init]: Vanilla Extract 설정

---

.prettierrc
eslint.config.js
package.json
pnpm-lock.yaml

> close #4
ESLint & Prettier 설정
- ESLint 설정
- Prettier 설정
[React 관련]
룰 | 설명
-- | --
`eslint-plugin-react` | JSX 문법 관련 규칙 검사
`eslint-plugin-react-hooks` | Hook 관련 규칙 (useEffect, useState 등 올바르게 사용했는지)
`eslint-plugin-react-refresh` | React Fast Refresh 최적화를 위한 검사
[코드 스타일]
룰 | 설명
-- | --
`eslint-plugin-import` | import 순서 검사 및 그룹별 구분
`eslint-plugin-prettier` | Prettier 포맷 위반 시 ESLint 에러로 표시
`eslint-config-prettier` | ESLint와 Prettier의 룰 충돌 방지
[커스텀 룰]
룰 | 설명
-- | --
`no-console: warn` | console.log 사용 시 경고
`@typescript-eslint/no-unused-vars: warn` | 사용하지 않는 변수 경고
`@typescript-eslint/no-explicit-any: warn` | any 타입 사용 시 경고
`curly: error` | if, for 등에 중괄호 꼭 쓰기
`import/order` | import 순서 정리하고 줄 간격 유지
`prettier/prettier: error` | Prettier 포맷 위반 시 에러 표시
`react/react-in-jsx-scope: off` | React 17+ …

[Init]: ESLint & Prettier 설정

---

.github/workflows/cd.yml

> close #issue_number
- Task 1
- Task 2

[Fix]: 자동 배포 커밋 메시지 간소화

---

.github/workflows/cd.yml
.github/workflows/ci.yml

> close #
로컬 개발 환경과 GitHub Actions 환경을 동일하게 맞춰서 빌드 오류를 해결했습니다.
- Node.js 버전 20 → 22로 변경 (로컬과 일치)
- pnpm 버전 중복 설정 제거
로컬에서는 빌드 성공하는데 GitHub Actions에서만 실패하는 문제가 해결되었는지 확인해 주세요 !

[Fix]: CI/CD 환경을 로컬과 동일하게 설정

---

eslint.config.js

> close #31
ESLint 키보드 이벤트 설정 해제
- 키보드 이벤트 설정 해제

[Fix]: 키보드 이벤트 설정 해제

---

src/shared/component/Layout/Header/Header.css.ts
src/shared/component/Layout/Header/Header.tsx
src/shared/component/Layout/Layout.tsx
src/style/global.css.ts
src/style/token/typography.css.ts

> #36 
- 임시 헤더 구현
- html의 font-size를 62.5% -> 100%
- 기존 rem 값 전체 수정(피그마 기준 px -> rem 직접 변환)
- 폰트 사이즈 적용 잘 되는지 확인 부탁합니닷

[Feat]: 임시 헤더 및 rem 값 수정

---

src/main.tsx
src/style/token/color.css.ts

> close #37
- 디자인 토큰 추가
gradient 토큰은 백그라운드 이미지로 사용하면 됩니다 !!
```css
backgroundImage: colors.gradient05
```

[Style]: 디자인 토큰 추가 

---

public/svg/ic_dropdown.svg
src/assets/svg/IcDropdown.tsx
src/assets/svg/index.ts
src/common/component/CycleDropDown/CycleDropDown.css.ts
src/common/component/CycleDropDown/CycleDropDown.tsx
src/common/component/CycleDropDown/CycleList.css.ts
src/common/component/CycleDropDown/CycleList.tsx
src/common/component/GoButton/GoButton.css.ts
src/common/component/MandalButton/MandalButton.css.ts
src/style/reset.css.ts
src/style/token/index.ts
src/style/token/zIndex.css.ts

> close #47 
- 주기 드롭다운 컴포넌트 제작
- 드롭다운 되었을 때의 컴포넌트 제작

[Feat]: 주기 드롭다운 컴포넌트 제작

---

pnpm-lock.yaml

[Fix]: 배포 빌드 오류 해결

---

src/page/mandal/component/Toggle/Toggle.css.ts
src/page/mandal/component/Toggle/Toggle.stories.tsx
src/page/mandal/component/Toggle/Toggle.tsx
src/page/mandal/component/Toggle/index.ts

> close #81 
- 만다라트 뷰의 토글 버튼 구현
ㅈㄱㄴ
https://github.com/user-attachments/assets/382fec8d-ec82-4443-9f18-9ae6e7416507

[Feat/#81] 토글버튼

---

src/page/home/Home.tsx
src/page/todo/myTodo/component/CycleChip/CycleChip.css.ts
src/page/todo/myTodo/component/CycleChip/CycleChip.tsx
src/page/todo/myTodo/component/CycleChip/CycleChip.types.ts
src/page/todo/myTodo/component/CycleChip/index.ts

> close #103 
cycleChip 컴포넌트를 구현합니다.
- cycleChip 컴포넌트 구현
조건부 렌더링으로
주기를 선택할 수 있는 칩은 `type === 'selector'` → `<button>`
주기 선택에 따라 `type === 'display'` → `<span>`
선택할 수 있도록 구현했습니다 !!

[Feature]: cycleChip 컴포넌트 구현

---

public/svg/ic_tomorrow.svg
public/svg/ic_yesterday.svg
src/assets/svg/IcTomorrow.tsx
src/assets/svg/IcYesterday.tsx
src/assets/svg/index.ts
src/common/util/format.ts
src/page/home/Home.tsx
src/page/mandal/Mandal.tsx
src/page/todo/myTodo/component/DatePicker/DatePicker.css.ts
src/page/todo/myTodo/component/DatePicker/DatePicker.tsx
src/page/todo/myTodo/component/DatePicker/index.ts

> close #97 
Date Picker 컴포넌트를 구현합니다.
- Date Picker 컴포넌트 구현
Home 페이지에서 DatePicker의 이전/다음 버튼 활성/비활성 및 아이콘 색상(active/inactive) 전환이 정상 동작하는지, 최소/최대 날짜 경계 조건까지 모두 테스트했습니다 !!

[Feat]: Date Picker 컴포넌트 구현

---

vercel.json

[Fix]: 버셀 로그인 문제 해결

---

src/page/home/EndSection/EndSection.tsx
src/page/home/Home.tsx
src/page/home/StartButton/StartButton.tsx
src/page/home/StartSection/StartSection.tsx
src/shared/component/Layout/layoutHeader/Header.css.ts
src/shared/component/Layout/layoutHeader/Header.tsx

> close #i146
- 헤더에 로그인 제거
- 랜딩 페이지에서 바로 투두 페이지로 이동

[Feat]: 라우터 수정

---

src/api/domain/myTodo/hook/useDeleteRecommendation.ts
src/api/domain/myTodo/hook/usePostRecommendation.ts
src/api/domain/myTodo/index.ts
src/api/domain/myTodo/type/recommendation.ts
src/page/todo/myTodo/hook/useMyTodo.ts

> close #153
- get: 맞춤 정보 데이터 불러오기 & 체크 사항 반영
- post: 완료했으면 check 
- delete: 완료 취소
https://github.com/user-attachments/assets/16dd61b2-7d0c-47d5-b5f5-f3e42d6b51ff

[Feat]: 맞춤 할일 추천

---

src/page/home/EndSection/EndSection.tsx
src/page/home/Home.tsx
src/page/home/StartButton/StartButton.tsx
src/page/home/StartSection/StartSection.tsx
src/shared/component/Layout/layoutHeader/Header.css.ts
src/shared/component/Layout/layoutHeader/Header.tsx

로그인 모달 연결 
> close #163
- Task 1
- Task 2

feat: 로그인 모달 연결

---

src/page/todo/upperTodo/UpperTodo.tsx

> close #52
- 요청이 두 번씩 가는 문제를 해결했어요.
- 바로 머지할게요

[Fix]: 요청 오류 해결

---

src/api/domain/lowerTodo/index.ts
src/common/component/AiFailModal/AiFailModal.tsx
src/page/todo/lowerTodo/LowerTodo.tsx
src/page/todo/lowerTodo/component/TodoFields.tsx

> close #
- AI 추천 값 받아오기
- AI 추천 값 만다라트에 추가 연결

[Feat]: AI 추천 값 만다라트에 추가 연결

---

src/api/constant/endPoint.ts
src/api/constant/queryKey.ts
src/api/domain/signup/hook/useGetPersona.ts
src/api/domain/signup/index.ts
src/api/domain/signup/type/PersonaResponse.ts
src/page/signup/SurveySection/SurveySection.tsx

[Feat]: 페르소나 API 연결

---

src/common/component/AiRecommendModal/AiRecommendModal.css.ts
src/common/component/AiRecommendModal/AiRecommendModal.tsx

> close #52 
- AI 추천 모달 스타일 수정

[Fix]: AI 추천 모달 스타일 수정

---

src/route/path.ts
src/shared/component/Layout/layoutFooter/Footer.tsx

> close #218 
- 이용약관, 개인정보처리방침에 외부 링크 연결
- 불필요한 TERMS, PRIVACY 경로 삭제

[Fix]: QA 반영 - 푸터 외부 링크 연결

---

src/common/component/Mandalart/Square/Square.tsx
src/common/component/TextField/modify/ModifyTextField.tsx

> close #220 
- 만다라트 박스 내 텍스트 23자 이상 작성 시 말줄임표 처리
- 수정하기 텍스트 필드에 30자 입력 제한 추가
- 영어, 숫자일 때도 줄바꿈 잘 되는지 확인 부탁드립니당😗
https://github.com/user-attachments/assets/008b1270-1bde-4b40-8ee8-f2b14d81b2a1

[Fix]: QA 반영 - 만다라트 박스

---

src/page/todo/myTodo/MyTodo.css.ts
src/page/todo/myTodo/component/DatePicker/DatePicker.css.ts
src/page/todo/myTodo/hook/useMyTodo.ts
src/shared/component/Layout/Layout.css.ts
src/style/global.css.ts

> close #214 
- useMyTodo.ts에서 미래 날짜로 이동을 제한하는 로직을 추가했습니다.
- 나의 할 일 뷰에서 전체 화면 스크롤 활성화 및 스크롤바 숨김 처리했습니다.
다음의 동작을 확인해 주시면 감사하겠습니다 !!
- 날짜 이동 시 미래 날짜로 이동 불가능
- 전체 화면에서 스크롤 작동 (양옆 영역에서도 스크롤 가능) + 스크롤바 노출 X

[Fix]: QA 반영 - 나의 할 일 뷰
